### ISSUE TITLE
no config/express.js

### ISSUE THREAD

**Issue by connor11528** [maartendb/angular-sails-scrum-tutorial#1]
I am trying to follow along. I generated a new sails app and there is no `config/express.js` file.

It looks like this is the current layout structure:

http://beta.sailsjs.org/#/documentation/anatomy/myApp/config

Also, can we serve up the angular app from the `assets` directory. I don't see how `mywebsite.com/angular/app` is best routing practice. Also don't know how to secure the API

Guidance would be cool. Am happy to contribute to the project as I learn more.

**Comment by TinChak** [comment]
I can't find the config/express.js file too. How do you solve the problem?
Thanks for your answer.

**Comment by butchewing** [comment]
Things have changed a bit in Sails 0.10. You have to add it to `config/http.js`. [Related answer](http://stackoverflow.com/questions/21807224/sailsjs-v0-10-express-custommiddleware-not-loading#answer-21807257)
